services:

  server:
    image: debian:server
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - shared:/mcookie/
    environment:
      - DISPLAY=:83
      - DEPTH=24
      - GEOMETRY=1366x768
      - VIEWONLY=false
      - VNCPASSWD=1234

  client:
    image: debian:client
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile

  app:
    image: debian:app
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    network_mode: host
    privileged: True
    environment:
      - DISPLAY=:83
      - GEOMETRY=1366x768
      - EXECUTABLE=notepad++.exe
    volumes: 
      - shared:/mcookie/
    depends_on:
      - client
      - server

volumes:
  shared:

